### ISSUE TITLE
Scopeguard missing no_std

### ISSUE THREAD

**Issue by esden** [kvverti/unaligned#1]
I was experimenting with this crate unfortunately the scopeguard dependency causes problems as it does not define `#![no_std]`.

Here is a snippet of the compile output:
```
   Compiling scopeguard v1.2.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabi` target may not support the standard library
  = note: `std` is required by `scopeguard` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: cannot find macro `stringify` in this scope
   --> /home/esdentem/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scopeguard-1.2.0/src/lib.rs:487:24
    |
487 |         f.debug_struct(stringify!(ScopeGuard))
    |                        ^^^^^^^^^
```

**Comment by kvverti** [comment]
I was today years old when I discovered that scopeguard includes std as a default feature. This will be remedied in the next update, but in the meantime you can override the Cargo.toml to disable scopeguard’s default features.

**Comment by esden** [comment]
Thank you for fixing this. :)
